propgroup/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from app import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

admin.site.site_header = 'Prop360d'
admin.site.site_title = "Prop360d Admin Portal"
admin.site.index_title = "Welcome to Prop360d Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('zone_list', views.zone_list,name="zone_list"),
    #path('saveroute', views.saveroute,name="saveroute"),
    path('location_list', views.location_list,name="location_list"),
    path('get_video_list', views.get_video_list,name="get_video_list"),
    #path('savelocationboundry', views.savelocationboundry,name="savelocationboundry"),
    path('save_drone_path_video', views.save_drone_path_video,name="save_drone_path_video"),
    path('ajax_login', views.ajax_login, name="ajax_login"),
    path('ajax_verify_otp', views.ajax_verify_otp, name="ajax_verify_otp"),
    path('ajax_send_otp', views.ajax_send_otp, name="ajax_send_otp"),
    path('ajax_register', views.ajax_register, name="ajax_register"),
    path('ajax_polygons', views.ajax_polygons, name="ajax_polygons"),
    path('ajax_location_polygons', views.ajax_location_polygons, name="ajax_location_polygons"),
    path('ajax_get_markers', views.ajax_get_markers, name="ajax_get_markers"),
    path('ajax_drone_video_paths', views.ajax_drone_video_paths, name="ajax_drone_video_paths"),
    path('ajax_get_video_list', views.ajax_get_video_list, name="ajax_get_video_list"),
    path('get_map_form', views.get_map_form, name="get_map_form"),
    path('save_map', views.save_map, name="save_map"),
    path('find_zone', views.find_zone, name="find_zone"),
    path('zones', views.zones, name="zones"),
    path('ajax_update_polygons', views.ajax_update_polygons, name="ajax_update_polygons"),
    path('city', views.city, name="city"),
    path('ajax_update_city', views.ajax_update_city, name="ajax_update_city"),
    path('ajax_select_city', views.ajax_select_city, name="ajax_select_city"),
    path('update_zone', views.update_zone, name="update_zone"),
    path('update_city', views.update_city, name="update_city"),
    path('drones', views.drones, name="drones"),
    path('update_drone', views.update_drone, name="update_drone"),
    path('logout', views.logout_view, name = 'logout'), 
]  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_exempt
from landmark.models import Landmark
from .models import State,City,Location,Zone
from projects.models import Project
from dronevideo.models import DroneVideo


class LandmarkForm(forms.ModelForm):
    name = forms.CharField(required=True, label='Name',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    latitude= forms.CharField(required=False,widget=forms.HiddenInput())
    longitude= forms.CharField(required=False,widget=forms.HiddenInput())
    icon = forms.FileField(required=True, label='icon') 
    image = forms.FileField(required=True, label='image') 
   

    class Meta:
        model = Landmark
        fields = ("name","description","state",'city','zone','latitude','longitude','icon','image')


class ProjectForm(forms.ModelForm):
    project_name = forms.CharField(required=True, label='Project Name',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    latitude= forms.CharField(required=False,widget=forms.HiddenInput())
    longitude= forms.CharField(required=False,widget=forms.HiddenInput())
    icon = forms.FileField(required=True, label='icon') 
    image = forms.FileField(required=True, label='image') 
   

    class Meta:
        model = Project
        fields = ("project_name","description","state",'city','zone','latitude','longitude','icon','image')



class DroneVideoForm(forms.ModelForm):
    title = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    video_url = forms.URLField(required=False, max_length=255,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    #path_color_code = forms.CharField(required=True, label='path_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))

    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
  
   

    class Meta:
        model = DroneVideo
        fields = ("title","video_url","description","state",'city','zone')


class ZoneForm(forms.ModelForm):
    zone_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    zone_color_code = forms.CharField(required=False, label='zone_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    name_color_code = forms.CharField(required=False, label='name_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    population = forms.CharField(required=False, label='population',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    area = forms.CharField(required=False, label='area',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    traffic = forms.CharField(required=False, label='traffic',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    
   

    class Meta:
        model = Zone
        fields = ("zone_name","zone_color_code","name_color_code","population","area","traffic","state",'city')


class CityForm(forms.ModelForm): 
    city_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    boundry_color_code = forms.CharField(required=False, label='boundry_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    map_fill_color_code = forms.CharField(required=False, label='map_fill_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    center_latitude = forms.CharField(required=False, label='center_latitude',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    center_longitude = forms.CharField(required=False, label='center_longitude',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    map_zoom = forms.IntegerField(required=False, label='map_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    map_min_zoom = forms.IntegerField(required=False, label='map_min_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    map_max_zoom = forms.IntegerField(required=False, label='map_max_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    
    
   

    class Meta:
        model = City
        fields = ("city_name","boundry_color_code","map_fill_color_code","center_latitude","center_longitude","map_zoom","map_min_zoom",'map_max_zoom','state')



class LocationForm(forms.ModelForm): 
    location_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    boundry_color_code = forms.CharField(required=False, label='boundry_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    fill_color_code = forms.CharField(required=False, label='fill_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    name_color_code = forms.CharField(required=False, label='name_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    
    
   

    class Meta:
        model = Location
        fields = ("location_name","boundry_color_code","fill_color_code","name_color_code","state","city",'zone')

templates/front/includes/auth_script.html
<script>

  $(document).ready(function () {
    $('#login_form').keypress(function (event) {
      if (event.keyCode === 13) {
        $('.submit_login').trigger("click");
      }
    });
    $('#register_form').keypress(function (event) {
      if (event.keyCode === 13) {
        $('.register_button').trigger("click");
      }
    });

    $('#verify_otp_form').keypress(function (event) {
      if (event.keyCode === 13) {
        $('.verify_otp').trigger("click");
      }
    });

    $(document).on("click", ".register_button", function () {
      form = document.getElementById('register_form');
      formdata = new FormData(form);
      $.ajax({
        url: "{% url 'ajax_register' %}",
        type: "POST",
        enctype: 'multipart/form-data',
        data: formdata,
        dataType: "json",
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function () {
          $("#register_button").html(`Please wait...`);
          $("#register_button").removeClass('register_button');
        },
        success: function (data) {
          var newUser = $('.register_div')
          var otpDiv = $('.otp_div')
          if (data.error == false) {
            newUser.hide();
            otpDiv.show();
            $("#user_number").text($("#mobile").val());
            $("#otpmobile").val($("#mobile").val());
            $("#verify_type").val("2")
            $("#temp_id").val(data.temp_id);
          } else {
            $("#register_button").html(`Signup`);
            $("#register_button").addClass('register_button');
            var response = "";
            response += '<div class="alert alert-danger messagess" role="alert">' + data.message + '</div>';
            $(".msg_div_reg").html(response);
          }
        },
      });


    });


    $(document).on("click", ".verify_otp", function () {

      form = document.getElementById('verify_otp_form');
      formdata = new FormData(form);
      $.ajax({
        url: "{% url 'ajax_verify_otp' %}",
        type: "POST",
        enctype: 'multipart/form-data',
        data: formdata,
        dataType: "json",
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function () {
          $("#verify_otp").html(`Please wait...`);
          $("#verify_otp").removeClass('verify_otp');
        },
        success: function (data) {

          if (data.error == false) {
            if (data.redirect_page) {
              window.location.href = "{% url 'dashboard' %}?" + data.redirect_page;
            } else {
              window.location.reload();
            }
          } else {
            $("#verify_otp").html(`Verify OTP`);
            $("#verify_otp").addClass('verify_otp');
            var response = "";
            response += '<div class="alert alert-danger messagess" role="alert">' + data.message + '</div>';
            $(".msg_div_otp").html(response);
          }
        },
      });

    });


    $(document).on("click", ".resend_otp", function () {
      var formdata = {
        'username': $("#otpmobile").val(),
        'verify_type': $("#verify_type").val(),
        'csrfmiddlewaretoken': '{{ csrf_token }}'  // Include CSRF token in the formdata
      };
      $.ajax({
        url: "{% url 'ajax_send_otp' %}",
        type: "POST",
        enctype: 'multipart/form-data',
        data: formdata,
        dataType: "json",
        headers: { "X-CSRFToken": "{{ csrf_token }}" },
        beforeSend: function () {
          $("#resend_otp").html(`Please wait...`);
          $("#resend_otp").removeClass('resend_otp');
        },
        success: function (data) {
          $("#resend_otp").html(`Resend OTP`);
          $("#resend_otp").addClass('resend_otp');
          var response = "";
          if (data.error == false) {
            response += '<div class="alert alert-success messagess" role="alert">' + data.message + '</div>';
          } else {
            response += '<div class="alert alert-danger messagess" role="alert">' + data.message + '</div>';
          }
          $(".msg_div_otp").html(response);
        },
      });

    });

    $(document).on("click", ".submit_login", function () {
      form = document.getElementById('login_form');
      formdata = new FormData(form);
      $.ajax({
        url: $("#login_form").attr("action"),
        type: "POST",
        enctype: 'multipart/form-data',
        data: formdata,
        dataType: "json",
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function () {
          $("#submit_login").html(`Wait...`);
          $("#submit_login").removeClass('submit_login');
        },
        success: function (data) {
          if (data.error == false) {
            if (data.redirect_page) {
              window.location.href = "{% url 'dashboard' %}?" + data.redirect_page;
            } else {
              window.location.reload();
            }
            //window.location.reload();

          } else {
            $("#submit_login").html(`Sign In`);
            $("#submit_login").addClass('submit_login');
            var response = "";
            response += '<div class="alert alert-danger messagess" role="alert">' + data.message + '</div>';
            $(".msg_div").html(response);
          }
        },
      });

    });

  });

</script>

templates/front/includes/footer.html
  <!-- Footer -->
  <footer class="bg-dark text-white py-4">
    <div class="container text-center">
        <p>&copy; 2024 Property Group. All rights reserved.</p>
        <p>
            <a href="#" class="text-white">Privacy Policy</a> | 
            <a href="#" class="text-white">Terms of Service</a>
        </p>
    </div>
</footer>

templates/front/includes/header.html
<div class="pxp-header pxp-full fixed-top">
    <div class="pxp-container-full">
        <div class="row align-items-center">
            <div class="col-5 col-md-2">
                <a href="/" class="pxp-logo text-decoration-none">Prop360d</a>
            </div>
            <div class="col-2 col-md-8 text-center">
                <ul class="pxp-nav list-inline">
                    <li class="list-inline-item">
                        {% if user.is_authenticated %}
                        {% if page_name == "dashboard" %}
                        <a href="#" onclick="take_action('2')">Project</a>
                        {%else%}
                        <a href="/dashboard?action_type=2">Project</a>
                        {% endif %}
                        {%else%}
                        <a href="#" action_id="2" class="pxp-signin-trigger">Project</a>
                        {% endif %}
                    </li>
                    <li class="list-inline-item">
                        {% if user.is_authenticated %}
                        {% if page_name == "dashboard" %}
                        <a href="#" onclick="take_action('3')">Drone Video</a>
                        {%else%}
                        <a href="/dashboard?action_type=3">Drone Video</a>
                        {% endif %}


                        {%else%}
                        <a href="#" action_id="3" class="pxp-signin-trigger">Drone Video</a>
                        {% endif %}


                    </li>

                    {% if user.is_authenticated and user.is_superuser %}
                    <li class="list-inline-item">
                        <a href="#">Manage Masters</a>
                        <ul class="pxp-nav-sub rounded-lg">
                            <li>
                                <a href="/zones">Zone Listing</a>
                            </li>
                            <li>
                                {% if page_name == "dashboard" %}
                                <a href="#" onclick="take_action('4')">Add Zone</a>
                                {%else%}
                                <a href="/dashboard?action_type=4">Add Zone</a>
                                {% endif %}
                            </li>
                            <li>
                                <a href="/city">City Listing</a>
                            </li>
                            <li>
                                {% if page_name == "dashboard" %}
                                <a href="#" onclick="take_action('5')">Add City</a>
                                {%else%}
                                <a href="/dashboard?action_type=5">Add City</a>
                                {% endif %}
                            </li>
                            <li>
                                <a href="/drones">Drone Videos</a>
                            </li>
                            <li>
                                {% if page_name == "dashboard" %}
                                <a href="#" onclick="take_action('6')">Add Location</a>
                                {%else%}
                                <a href="/dashboard?action_type=6">Add Location</a>
                                {% endif %}
                            </li>
                        </ul>
                    </li>
                    {% endif %}


                    <li class="list-inline-item">
                        <a href="#">Blog</a>
                        <!-- <ul class="pxp-nav-sub rounded-lg">
                            <li><a href="#">All Blog Posts</a></li>
                            <li><a href="single-post.html">Single Blog Post</a></li>
                        </ul> -->
                    </li>

                    
                    <li class="list-inline-item pxp-is-last"><a href="#">Contact Us</a></li>
                     
                    {%if city_listing %}
                    <li class="list-inline-item">
                        <a href="#">City</a>
                        <ul class="pxp-nav-sub rounded-lg">
                            {% for city in city_listing %}
                            <li><a href="#" class="choose_city" city_id="{{city.id}}" >{{city.city_name}}</a></li>
                            {% endfor %}
                        </ul>
                    </li>
                    {% endif %}

                    {% if user.is_authenticated %}
                    <li class="list-inline-item pxp-is-last"><a href={% url 'logout' %}>Logout</a></li>
                    {% endif %}

                    <li class="list-inline-item pxp-has-btns">



                        <div class="pxp-user-btns">
                            {% if user.is_authenticated %}
                            <a href="/dashboard" class="pxp-user-btns-signup ">Dashboard</a>
                            <a href={% url 'logout' %} class="pxp-user-btns-login ">Logout</a>
                            {%else%}
                            <a href="#" class="pxp-user-btns-signup pxp-signup-trigger">Sign Up</a>
                            <a href="#" action_id="" class="pxp-user-btns-login pxp-signin-trigger">Sign In</a>
                            {% endif %}
                        </div>

                    </li>

                </ul>
            </div>
            {% if user.is_authenticated %}
            <div class="col-5 col-md-2 text-right">

                <a href="javascript:void(0);" class="pxp-header-nav-trigger"><span class="fa fa-bars"></span></a>
                <a href="/dashboard" class="pxp-header-user pxp-signin-trigger"><span class="fa fa-user-o"></span></a>

            </div>

            {%else%}
            <div class="col-5 col-md-2 text-right">

                <a href="javascript:void(0);" class="pxp-header-nav-trigger"><span class="fa fa-bars"></span></a>
                <a href="javascript:void(0);" class="pxp-header-user pxp-signin-trigger"><span
                        class="fa fa-user-o"></span></a>

            </div>
            {% endif %}
        </div>
    </div>
</div>

templates/front/includes/map_forms.html
{% load static %}
<h5 class="modal-title" id="pxpSigninModal">{{page_title}}</h5>

<form id="map_form" enctype="multipart/form-data" class="mt-4" action={% url 'save_map' %} method='POST'>
    {% csrf_token %}
    <input type="hidden" name="action_type" value="{{action_type}}" id="id_action_type">
    {% if action_type == "1" %}
    {{map_form.latitude}}
    {{map_form.longitude}}


    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">
    <input type="hidden" name="zone" value="1" id="id_zone">

    <div class="form-group">
        <label for="id_name">Title</label>
        {{map_form.name}}
    </div>
    <div class="form-group">
        <label for="id_description">Description</label>
        {{map_form.description}}
    </div>
    <div class="form-group">
        <label for="id_icon">Map Icon</label>
        {{map_form.icon}}
    </div>

    <div class="form-group">
        <label for="id_icon">Image</label>
        {{map_form.image}}
    </div>

    {% elif action_type == "2" %}
    {{map_form.latitude}}
    {{map_form.longitude}}


    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">
    <input type="hidden" name="zone" value="1" id="id_zone">

    <div class="form-group">
        <label for="id_name">Project Name</label>
        {{map_form.project_name}}
    </div>
    <div class="form-group">
        <label for="id_description">Description</label>
        {{map_form.description}}
    </div>
    <div class="form-group">
        <label for="id_icon">Map Icon</label>
        {{map_form.icon}}
    </div>

    <div class="form-group">
        <label for="id_icon">Image</label>
        {{map_form.image}}
    </div>
    {% elif action_type == "3" %}
    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">
    <input type="hidden" name="zone" value="1" id="id_zone">

    <div class="form-group">
        <label for="id_name">Youtube URL</label>
        {{map_form.video_url}}
    </div>
    <div class="form-group">
        <label for="id_name">Title</label>
        {{map_form.title}}
    </div>
    <div class="form-group">
        <label for="id_description">Description</label>
        {{map_form.description}}
    </div>
    {% elif action_type == "4" %}
    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">



    <div class="form-group">
        <label for="id_name">Zone Name</label>
        {{map_form.zone_name}}
    </div>
    <div class="form-group">
        <label for="id_description">Zone Color Code (Hex Code)</label>
        {{map_form.zone_color_code}}
    </div>
    <div class="form-group">
        <label for="id_name">Name Color Code (HEX Code)</label>
        {{map_form.name_color_code}}
    </div>
    <div class="form-group">
        <label for="id_name">Population</label>
        {{map_form.population}}
    </div>
    <div class="form-group">
        <label for="id_name">Area</label>
        {{map_form.area}}
    </div>
    <div class="form-group">
        <label for="id_name">Traffic</label>
        {{map_form.traffic}}
    </div>

    {% elif action_type == "5" %}
    <input type="hidden" name="state" value="1" id="id_state">
    <div class="form-group">
        <label for="id_city_name">City Name</label>
        {{map_form.city_name}}
    </div>
    <div class="form-group">
        <label for="id_boundry_color_code">Boundry Color Code</label>
        {{map_form.boundry_color_code}}
    </div>
    <div class="form-group">
        <label for="id_map_fill_color_code">Map Fill Color Code</label>
        {{map_form.map_fill_color_code}}
    </div>
    <div class="form-group">
        <label for="id_center_latitude">Center Latitude</label>
        {{map_form.center_latitude}}
    </div>
    <div class="form-group">
        <label for="id_center_longitude">Center Longitude</label>
        {{map_form.center_longitude}}
    </div>
    <div class="form-group">
        <label for="id_map_zoom">Map Zoom</label>
        {{map_form.map_zoom}}
    </div>

    <div class="form-group">
        <label for="id_map_min_zoom">Map Min Zoom</label>
        {{map_form.map_min_zoom}}
    </div>

    <div class="form-group">
        <label for="id_map_max_zoom">Map Max Zoom</label>
        {{map_form.map_max_zoom}}
    </div>
    {% elif action_type == "6" %}
    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">
    <input type="hidden" name="zone" value="1" id="id_zone">


    <div class="form-group">
        <label for="id_location_name">Location Name</label>
        {{map_form.location_name}}
    </div>
    <div class="form-group">
        <label for="id_boundry_color_code">Boundry Color Code (Hex Code)</label>
        {{map_form.boundry_color_code}}
    </div>
    <div class="form-group">
        <label for="id_fill_color_code">Fill Color Code (Hex Code)</label>
        {{map_form.fill_color_code}}
    </div>
    <div class="form-group">
        <label for="id_name_color_code">Name Color Code (HEX Code)</label>
        {{map_form.name_color_code}}
    </div>
    

    {% else %}
    <input type="hidden" name="state" value="1" id="id_state">
    <input type="hidden" name="city" value="1" id="id_city">



    <div class="form-group">
        <label for="id_name">Zone Name</label>
        {{map_form.zone_name}}
    </div>
    <div class="form-group">
        <label for="id_description">Zone Color Code (Hex Code)</label>
        {{map_form.zone_color_code}}
    </div>
    <div class="form-group">
        <label for="id_name">Name Color Code (HEX Code)</label>
        {{map_form.name_color_code}}
    </div>
    <div class="form-group">
        <label for="id_name">Population</label>
        {{map_form.population}}
    </div>
    <div class="form-group">
        <label for="id_name">Area</label>
        {{map_form.area}}
    </div>
    <div class="form-group">
        <label for="id_name">Traffic</label>
        {{map_form.traffic}}
    </div>
    {% endif %}
    <div class="form-group">
        <button type="button" class="pxp-agent-contact-modal-btn submit_map" id="submit_map">Submit</button>


    </div>
    <span style="width: 100%; text-align: center;margin-top: 5px;" class="msg_div_map"></span>


</form>