propgroup/urls.py
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf import settings
from django.conf.urls.static import static
from app import views
from django.views.generic import TemplateView
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

admin.site.site_header = 'Prop360d'
admin.site.site_title = "Prop360d Admin Portal"
admin.site.index_title = "Welcome to Prop360d Portal"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name="index"),
    path('dashboard', views.dashboard, name="dashboard"),
    path('zone_list', views.zone_list,name="zone_list"),
    #path('saveroute', views.saveroute,name="saveroute"),
    path('location_list', views.location_list,name="location_list"),
    path('get_video_list', views.get_video_list,name="get_video_list"),
    #path('savelocationboundry', views.savelocationboundry,name="savelocationboundry"),
    path('save_drone_path_video', views.save_drone_path_video,name="save_drone_path_video"),
    path('ajax_login', views.ajax_login, name="ajax_login"),
    path('ajax_verify_otp', views.ajax_verify_otp, name="ajax_verify_otp"),
    path('ajax_send_otp', views.ajax_send_otp, name="ajax_send_otp"),
    path('ajax_register', views.ajax_register, name="ajax_register"),
    path('ajax_polygons', views.ajax_polygons, name="ajax_polygons"),
    path('ajax_location_polygons', views.ajax_location_polygons, name="ajax_location_polygons"),
    path('ajax_get_markers', views.ajax_get_markers, name="ajax_get_markers"),
    path('ajax_drone_video_paths', views.ajax_drone_video_paths, name="ajax_drone_video_paths"),
    path('ajax_get_video_list', views.ajax_get_video_list, name="ajax_get_video_list"),
    path('get_map_form', views.get_map_form, name="get_map_form"),
    path('save_map', views.save_map, name="save_map"),
    path('find_zone', views.find_zone, name="find_zone"),
    path('zones', views.zones, name="zones"),
    path('ajax_update_polygons', views.ajax_update_polygons, name="ajax_update_polygons"),
    path('city', views.city, name="city"),
    path('ajax_update_city', views.ajax_update_city, name="ajax_update_city"),
    path('ajax_select_city', views.ajax_select_city, name="ajax_select_city"),
    path('update_zone', views.update_zone, name="update_zone"),
    path('update_city', views.update_city, name="update_city"),
    path('drones', views.drones, name="drones"),
    path('update_drone', views.update_drone, name="update_drone"),
    path('logout', views.logout_view, name = 'logout'), 
]  
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.views.decorators.csrf import csrf_exempt
from landmark.models import Landmark
from .models import State,City,Location,Zone
from projects.models import Project
from dronevideo.models import DroneVideo


class LandmarkForm(forms.ModelForm):
    name = forms.CharField(required=True, label='Name',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    latitude= forms.CharField(required=False,widget=forms.HiddenInput())
    longitude= forms.CharField(required=False,widget=forms.HiddenInput())
    icon = forms.FileField(required=True, label='icon') 
    image = forms.FileField(required=True, label='image') 
   

    class Meta:
        model = Landmark
        fields = ("name","description","state",'city','zone','latitude','longitude','icon','image')


class ProjectForm(forms.ModelForm):
    project_name = forms.CharField(required=True, label='Project Name',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    latitude= forms.CharField(required=False,widget=forms.HiddenInput())
    longitude= forms.CharField(required=False,widget=forms.HiddenInput())
    icon = forms.FileField(required=True, label='icon') 
    image = forms.FileField(required=True, label='image') 
   

    class Meta:
        model = Project
        fields = ("project_name","description","state",'city','zone','latitude','longitude','icon','image')



class DroneVideoForm(forms.ModelForm):
    title = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    video_url = forms.URLField(required=False, max_length=255,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    #path_color_code = forms.CharField(required=True, label='path_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))

    description = forms.CharField(required=True, label='Description',max_length=80,widget=forms.TextInput(attrs={'class': 'form-control'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
  
   

    class Meta:
        model = DroneVideo
        fields = ("title","video_url","description","state",'city','zone')


class ZoneForm(forms.ModelForm):
    zone_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    zone_color_code = forms.CharField(required=False, label='zone_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    name_color_code = forms.CharField(required=False, label='name_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    population = forms.CharField(required=False, label='population',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    area = forms.CharField(required=False, label='area',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    traffic = forms.CharField(required=False, label='traffic',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    
   

    class Meta:
        model = Zone
        fields = ("zone_name","zone_color_code","name_color_code","population","area","traffic","state",'city')


class CityForm(forms.ModelForm): 
    city_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    boundry_color_code = forms.CharField(required=False, label='boundry_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    map_fill_color_code = forms.CharField(required=False, label='map_fill_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    center_latitude = forms.CharField(required=False, label='center_latitude',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    center_longitude = forms.CharField(required=False, label='center_longitude',max_length=20,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    map_zoom = forms.IntegerField(required=False, label='map_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    map_min_zoom = forms.IntegerField(required=False, label='map_min_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    map_max_zoom = forms.IntegerField(required=False, label='map_max_zoom',widget=forms.TextInput(attrs={'class': 'form-control alphaonly'})) 
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    
    
   

    class Meta:
        model = City
        fields = ("city_name","boundry_color_code","map_fill_color_code","center_latitude","center_longitude","map_zoom","map_min_zoom",'map_max_zoom','state')



class LocationForm(forms.ModelForm): 
    location_name = forms.CharField(required=True, label='Title',max_length=50,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    boundry_color_code = forms.CharField(required=False, label='boundry_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    fill_color_code = forms.CharField(required=False, label='fill_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    name_color_code = forms.CharField(required=False, label='name_color_code',max_length=7,widget=forms.TextInput(attrs={'class': 'form-control alphaonly'}))
    state=forms.ModelChoiceField(required=False, 
        queryset=State.objects.filter(is_active=True),empty_label="Select State",widget=forms.Select(attrs={'class': 'form-control'})) 
    city=forms.ModelChoiceField(required=False, 
        queryset=City.objects.filter(is_active=True),empty_label="Select City",widget=forms.Select(attrs={'class': 'form-control'})) 
    zone=forms.ModelChoiceField(required=False, 
        queryset=Zone.objects.filter(is_active=True),empty_label="Select Zone",widget=forms.Select(attrs={'class': 'form-control'})) 
    
    
   

    class Meta:
        model = Location
        fields = ("location_name","boundry_color_code","fill_color_code","name_color_code","state","city",'zone')

templates/front/city.html
{% extends "front/base.html" %}{% block content %} {% load static %}
<div class="pxp-content pxp-full-height city">
    <div class="pxp-content-side pxp-content-left pxp-half">
       
            
        <div class="pxp-content-side-wrapper">
          {% if record %}
          <div class="table-responsive" style="height: 200px;">
          {%else%}
          <div class="table-responsive">
          {%endif%}
                    <table class="table table-bordered table-striped table-hover">
                        <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>City</th>
                                <th>State</th>
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        {% if listing%}
                        <tbody>
                        {%for list in listing %}
                            <tr>
                                <td>{{list.id}}</td>
                                <td>{{list.city_name}}</td>
                                <td>{{list.state.state_name}}</td>
                                <td>{{list.is_active}}</td>
                                <td>
                                    <a href="/city?action=edit&id={{list.id}}"><button class="btn btn-primary btn-sm">Edit</button></a>
                                    <!-- <button class="btn btn-danger btn-sm">Delete</button> -->
                                </td>
                            </tr>
                            {%endfor%}
                           
                            
                        </tbody>
                        {%endif%}
                    </table>
                </div>
                {% if id %}
                <div class="edit_form">
                  <form id="map_form" enctype="multipart/form-data" class="mt-4" action={% url 'update_city' %} method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{id}}">
                    <div class="form-group">
                      <label for="id_city_name">City Name</label>
                      {{map_form.city_name}}
                  </div>
                  <div class="form-group">
                      <label for="id_boundry_color_code">Boundry Color Code</label>
                      {{map_form.boundry_color_code}}
                  </div>
                  <div class="form-group">
                      <label for="id_map_fill_color_code">Map Fill Color Code</label>
                      {{map_form.map_fill_color_code}}
                  </div>
                  <div class="form-group">
                      <label for="id_center_latitude">Center Latitude</label>
                      {{map_form.center_latitude}}
                  </div>
                  <div class="form-group">
                      <label for="id_center_longitude">Center Longitude</label>
                      {{map_form.center_longitude}}
                  </div>
                  <div class="form-group">
                      <label for="id_map_zoom">Map Zoom</label>
                      {{map_form.map_zoom}}
                  </div>
              
                  <div class="form-group">
                      <label for="id_map_min_zoom">Map Min Zoom</label>
                      {{map_form.map_min_zoom}}
                  </div>
              
                  <div class="form-group">
                      <label for="id_map_max_zoom">Map Max Zoom</label>
                      {{map_form.map_max_zoom}}
                  </div> 
            
                  <div class="form-group">
                    <button type="button" class="pxp-agent-contact-modal-btn updatet_map" id="updatet_map">Submit</button>
            
            
                  </div>
                  <span style="width: 100%; text-align: center;margin-top: 5px;" class="msg_div_map"></span>
                </form>
                </div>

                {% endif %}

            </div>
       
    </div>
    <div class="pxp-map-side pxp-map-right pxp-half">
        <div id="map"></div>
    </div>
</div>

<script>
    let map;
    let polygon;
    $(document).ready(function () {
        initMapZone();
        $(document).on("click", ".updatet_map", function () {
      form = document.getElementById("map_form");
      formdata = new FormData(form);
      


      $.ajax({
        url: $("#map_form").attr("action"),
        type: "POST",
        enctype: "multipart/form-data",
        data: formdata,
        dataType: "json",
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function () {
          $("#updatet_map").html("Wait..");
          
        },
        success: function (data) {
          var response = "";
          $("#updatet_map").html(
            `Submit`
          );
          $("#updatet_map").addClass("updatet_map");
          if (data.error == false) {
            response +=
              '<div class="alert alert-success" role="alert">' +
              data.message +
              "</div>";
            
            $(".msg_div_map").html(response);
            window.location.reload();
          } else {

            var resp = data.errors;
            if (data.message == "") {
              $.each(resp, function (k, value) {
                response +=
                  '<div class="alert alert-danger" role="alert">' +
                  k +
                  " : " +
                  value +
                  `</div>`;
              });
            } else {
              response +=
                '<div class="alert alert-danger" role="alert">' +
                data.message +
                "</div>";
            }
            $(".msg_div_map").html(response);

          }
        },
      });

    });
    });
    document.addEventListener("DOMContentLoaded", function () {
    const windowHeight = window.innerHeight;
    const div = document.getElementById('map');
    div.style.height = `${window.innerHeight - 100}px`;
  });
  function getPolygonCenter(coords) {
    var latSum = 0;
    var lngSum = 0;
    coords.forEach(function (coord) {
      latSum += coord.lat;
      lngSum += coord.lng;
    });
    return {
      lat: latSum / coords.length,
      lng: lngSum / coords.length
    };
  }
    function initMapZone() {
      {% if record %}
      const polygonCoords = {{record.boundry_json|safe}};
      var polygonCenter = getPolygonCenter(polygonCoords);
      map = new google.maps.Map(document.getElementById("map"), {
        center: { lat: polygonCenter.lat, lng: polygonCenter.lng }, // San Francisco
        zoom: parseInt("{{record.map_zoom}}"),
        minZoom:parseInt("{{record.map_min_zoom}}"),          // Minimum zoom level allowed
        maxZoom: parseInt("{{record.map_max_zoom}}"),         // Maximum zoom level allowed
      });
      {%else%}
     var center = {lat: {{center_latitude}}, lng: {{center_longitude}}};
     map = new google.maps.Map(document.getElementById("map"), {
        center: center, // San Francisco
        zoom:8,
        minZoom:5,          // Minimum zoom level allowed
        maxZoom: 20,         // Maximum zoom level allowed
      });
    {%endif%}
     

      // Define the polygon's initial coordinates
      {% if record %} 
      map_fill_color_code="{{map_fill_color_code}}";
      if(map_fill_color_code){
        fillOpacity=0.35;
      }else{
        fillOpacity=0;
      }
      // Create the polygon
      polygon = new google.maps.Polygon({
        paths: polygonCoords,
        editable: true, // Make the polygon editable
        draggable: false, // Allow dragging
        strokeColor: "{{boundry_color_code}}",
        strokeOpacity: 0.8,
        strokeWeight: 2,
        fillColor: "{{map_fill_color_code}}",
        fillOpacity: fillOpacity,
      });

      // Add the polygon to the map
      polygon.setMap(map);

      // Add event listeners to log the polygon's coordinates
      google.maps.event.addListener(polygon.getPath(), "set_at", logPolygonCoords);
      google.maps.event.addListener(polygon.getPath(), "insert_at", logPolygonCoords);

      logPolygonCoords(); // Log the initial coordinates
      {%endif%}

      const polygonsData = {{ city_data| safe}};
      polygonsData.forEach((polygonData, index) => {
      var fillOpacity = polygonData.map_fill_color_code ? 0.35 : 0;


      var polygon = new google.maps.Polygon({
        paths: polygonData.coords,
        strokeColor: polygonData.color,
        strokeOpacity: 2,
        strokeWeight: 2,
        fillColor: polygonData.map_fill_color_code,
        fillOpacity: fillOpacity,
        clickable: false,
      });
      // Display the polygon on the map
      polygon.setMap(map);
    });
    }

    // Function to log the polygon's coordinates
    function logPolygonCoords() {
      const path = polygon.getPath();
      const coordinates = [];

      for (let i = 0; i < path.getLength(); i++) {
        const latLng = path.getAt(i);
        coordinates.push({ lat: latLng.lat(), lng: latLng.lng() });
      }

      console.log("Polygon Coordinates:", coordinates);

            $.ajax({
            url: "{% url 'ajax_update_city' %}",
            type: "POST",
            data: {
                "id": "{{record.id}}",
                "boundry_json": JSON.stringify(coordinates),
                "csrfmiddlewaretoken": "{{ csrf_token }}"
            },
            dataType: "json",
            beforeSend: function () {

            },
            success: function (data) {

                //window.location.reload();

            },
            });
    }
  </script>

{% endblock %}

templates/front/dashboard.html
{% extends "front/base.html" %}{% block content %} {% load static %}

{% endblock %}

templates/front/drones.html
{% extends "front/base.html" %}{% block content %} {% load static %}
<div class="pxp-content pxp-full-height">
    <div class="pxp-content-side pxp-content-left pxp-half">
       
            
        <div class="pxp-content-side-wrapper">
          {% if record %}
          <div class="table-responsive" style="height: 200px;">
          {%else%}
          <div class="table-responsive">
          {%endif%}
                    <table class="table table-bordered table-striped table-hover">
                        <thead class="table-dark">
                            <tr>
                                <th>#</th>
                                <th>Video</th>
                                <th>Title</th>
                                <!-- <th>City</th>
                                <th>State</th> -->
                                <th>Status</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        {% if listing%}
                        <tbody>
                        {%for list in listing %}
                            <tr>
                                <td>{{list.id}}</td>
                                <td>{{list.video_url}}</td>
                                <td>{{list.title}}</td>
                                <!-- <td>{{list.city.city_name}}</td>
                                <td>{{list.state.state_name}}</td> -->
                                <td>{{list.is_active}}</td>
                                <td>
                                    <a href="/drones?action=edit&id={{list.id}}"><button class="btn btn-primary btn-sm">Edit</button></a>
                                    <!-- <button class="btn btn-danger btn-sm">Delete</button> -->
                                </td>
                            </tr>
                            {%endfor%}
                           
                            
                        </tbody>
                        {%endif%}
                    </table>
                </div>
                {% if id %}
                <div class="edit_form">
                  <form id="map_form" enctype="multipart/form-data" class="mt-4" action={% url 'update_drone' %} method='POST'>
                    {% csrf_token %}
                    <input type="hidden" name="id" value="{{id}}">
                    <div class="form-group">
                      <label for="id_city_name">Title</label>
                      {{map_form.title}}
                  </div>
                  <div class="form-group">
                      <label for="id_video_url">Video url</label>
                      {{map_form.video_url}}
                  </div>
                  <div class="form-group">
                      <label for="id_description">Description</label>
                      {{map_form.description}}
                  </div>
                  
              
                
            
                  <div class="form-group">
                    <button type="button" class="pxp-agent-contact-modal-btn updatet_map" id="updatet_map">Submit</button>
            
            
                  </div>
                  <span style="width: 100%; text-align: center;margin-top: 5px;" class="msg_div_map"></span>
                </form>
                </div>

                {% endif %}

            </div>
       
    </div>
    <div class="pxp-map-side pxp-map-right pxp-half">
        <div id="map"></div>
    </div>
</div>

<script>
    let map;
    let polygon;
    $(document).ready(function () {
    initMapZone();
    $(document).on("click", ".updatet_map", function () {
      form = document.getElementById("map_form");
      formdata = new FormData(form);
      


      $.ajax({
        url: $("#map_form").attr("action"),
        type: "POST",
        enctype: "multipart/form-data",
        data: formdata,
        dataType: "json",
        cache: false,
        contentType: false,
        processData: false,
        beforeSend: function () {
          $("#updatet_map").html("Wait..");
          
        },
        success: function (data) {
          var response = "";
          $("#updatet_map").html(
            `Submit`
          );
          $("#updatet_map").addClass("updatet_map");
          if (data.error == false) {
            response +=
              '<div class="alert alert-success" role="alert">' +
              data.message +
              "</div>";
            
            $(".msg_div_map").html(response);
            window.location.reload();
          } else {

            var resp = data.errors;
            if (data.message == "") {
              $.each(resp, function (k, value) {
                response +=
                  '<div class="alert alert-danger" role="alert">' +
                  k +
                  " : " +
                  value +
                  `</div>`;
              });
            } else {
              response +=
                '<div class="alert alert-danger" role="alert">' +
                data.message +
                "</div>";
            }
            $(".msg_div_map").html(response);

          }
        },
      });

    });
    });
    document.addEventListener("DOMContentLoaded", function () {
    const windowHeight = window.innerHeight;
    const div = document.getElementById('map');
    div.style.height = `${window.innerHeight - 100}px`;
  });
  function getPolygonCenter(coords) {
    var latSum = 0;
    var lngSum = 0;
    coords.forEach(function (coord) {
      latSum += coord.lat;
      lngSum += coord.lng;
    });
    return {
      lat: latSum / coords.length,
      lng: lngSum / coords.length
    };
  }
    function initMapZone() {
      
     var center = {lat: parseFloat("{{center_latitude}}"), lng: parseFloat("{{center_longitude}}")};
     map = new google.maps.Map(document.getElementById("map"), {
        center: center, // San Francisco
        zoom:parseInt("{{city_info.map_zoom}}"),
        minZoom:parseInt("{{city_info.map_min_zoom}}"),          // Minimum zoom level allowed
        maxZoom: parseInt("{{city_info.map_max_zoom}}"),         // Maximum zoom level allowed
      });
      let pathData_color = "#008000";
     
      var paths = {{drone_data|safe}};
        paths.forEach((pathData, index) => {
          var pathPolyline = new google.maps.Polyline({
            path: pathData.coordinates,
            strokeColor: pathData_color,//pathData.color,
            strokeOpacity: 1,
            strokeWeight: 3,
            icons: [
              {
                // icon: {
                //   path: google.maps.SymbolPath.CIRCLE,
                //   scale: 3,
                //   fillColor: pathData_color,
                //   fillOpacity: 1,
                //   strokeWeight: 0,
                // },
                // icon: {
                //   url: "{% static 'front/images/camera.png' %}", // Replace with the path to your image
                //   scaledSize: new google.maps.Size(20, 20), // Adjust icon size
                //   anchor: new google.maps.Point(10, 10), // Center the icon
                // },
                offset: "0",
                repeat: "7px",
              },
            ],
            zIndex: 2099,
          });

          // Display the polyline on the map
          pathPolyline.setMap(map);
          var drone_path = pathData.coordinates;
          drone_path.forEach(function (markerData, index) {
            if (index === 0) {
              // First marker
              iconUrl = "{% static 'front/images/first_drone.png' %}";
            } else if (index === drone_path.length - 1) {
              // Last marker
              iconUrl = "{% static 'front/images/last_drone.png' %}";
            } else {
              // Middle markers
              iconUrl = "{% static 'front/images/drone.png' %}";
            }

            var drone = new google.maps.Marker({
              position: { lat: markerData.lat, lng: markerData.lng },
              map: map,
              icon: {
                url: iconUrl, // URL to the custom icon image
                scaledSize: new google.maps.Size(12, 12), // Scale the icon to desired size
                origin: new google.maps.Point(0, 0), // Origin point of the icon
                anchor: new google.maps.Point(5, 5) // Anchor point of the icon (centered)
              }
            });
          });

          // Add mouseover event for each polyline
          google.maps.event.addListener(pathPolyline, 'mouseover', function (event) {
            document.getElementById("customInfoWindow").style.display = "block";
            // document.getElementById("video_container").innerHTML = pathData.html_data;
            // document.getElementById("video_info").innerHTML = pathData.info;
            // document.getElementById("video_title").innerHTML = pathData.title;
            $("#dynamic_content").html(pathData.html_data);
          });

          google.maps.event.addListener(pathPolyline, 'click', function (event) {
            document.getElementById("customInfoWindow").style.display = "block";
            // document.getElementById("video_container").innerHTML = pathData.html_data;
            // document.getElementById("video_info").innerHTML = pathData.info;
            // document.getElementById("video_title").innerHTML = pathData.title;
            $("#dynamic_content").html(pathData.html_data);
          });

          // Add mouseout event to hide the info window when the mouse leaves the polyline
          google.maps.event.addListener(pathPolyline, 'mouseout', function () {
            //document.getElementById("customInfoWindow").style.display = "none";
          });
        });
     

   

      
    }

   
  </script>

{% endblock %}